FROM arm32v7/python:3.7-buster

WORKDIR /app

# copy files needed by docker
COPY ["./app/app.py", "docker-entrypoint.sh", "./app/requirements.txt", "docker-entrypoint.sh", "./"]

# install python modules
RUN pip3 install --no-cache-dir -r requirements.txt

# run script to set up default config if non existing, then start
CMD [ "/bin/bash", "/app/docker-entrypoint.sh", "python3", "/app/app.py" ]